### ISSUE TITLE
Client does not return flags - self hosted api server

### ISSUE THREAD

**Issue by ukabu** [SolidStateGroup/bullet-train-js-client#3] opened 2018-12-17 20:35 UTC
I initialized the client with :
```
bulletTrain.init({
        api,
        environmentID,
        onChange: handleFlags,
        onError: handleErrors,
        defaultFlags
      })
// api="https://bullet-train-api-experiment...com/api/v1/"
// environmentID="m...G"
// defaultFlags={
//    hello_world: true
// }
  handleFlags = (flags, params) => {
    this.setState({ flags })
    console.log(flags, params, bulletTrain.getAllFlags())
  }
```
In the console (from the handleFlag listener) I get : `{}, {isFromServer: true}, {}`

The response I get from the API server is :
```
[{"id":2,"feature":{"id":1,"name":"hello_world","created_date":"2018-12-11T20:55:38.891097Z","initial_value":null,"description":null,"default_enabled":false,"type":"FLAG","project":1},"feature_state_value":null,"enabled":true,"environment":2,"identity":null}]
```
if I call `bulletTrain.hasFeature("hello_world")` I always get `false`.

**Comment by kyle-ssg** [comment] 2018-12-17 22:08
Can you confirm this is due to using a self hosted api? I feel like this is a duplicate of https://github.com/SolidStateGroup/bullet-train-js-client/issues/2

**Comment by ukabu** [comment] 2018-12-18 16:15
The code seems wrong, in bullet-train-core, this calls the handleResponse(res) function, the response from the API is an array: https://github.com/SolidStateGroup/bullet-train-js-client/blob/f96cb36aabc8e77dabf790e36b78dbc9f898ec45/bullet-train-core.js#L65

But the `handleResponse` expect an object with the shape `{flags: [], traits: []}`: https://github.com/SolidStateGroup/bullet-train-js-client/blob/f96cb36aabc8e77dabf790e36b78dbc9f898ec45/bullet-train-core.js#L31

For reference, the bullet-train-fronend app interpret the response from the API as an array: https://github.com/SolidStateGroup/bullet-train-frontend/blob/e062cfd406e85c0220c2759556129a0776ae9975/web/components/TryIt.js#L22

**Comment by ukabu** [comment] 2018-12-18 16:25
Here is the commit that switch the handling from an array to an object: https://github.com/SolidStateGroup/bullet-train-js-client/commit/5c131e0254ecabf3679e2e038456b1aeb73f684e

**Comment by kyle-ssg** [comment] 2018-12-18 16:25
The response from getting flags is not an array since implementing user traits it has always been an object are you sure you're API is setup correctly and you are using the latest version?

```
curl 'https://api.bullet-train.io/api/v1/identities/bullet_train_sample_user/?format=json' -H 'x-environment-key: QjgYur4LQTwe5HpvbvhpzK' -H 'Referer: http://localhost:3000/' -H 'Origin: http://localhost:3000' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Content-Type: application/json; charset=utf-8' --compressed
```

**Comment by ukabu** [comment] 2018-12-18 16:38
Looks like my api server is not up to date. It's a bummer that the api changes in incompatible ways like that.
I will update my server and test it.

**Comment by ukabu** [comment] 2018-12-18 21:17
Now i'm running that latest api server from github and I still get an array
```
curl 'https://bullet-train-api-experiment.....com/api/v1/flags/?format=json' -H 'x-environment-key: m...G' -H 'Referer: http://localhost:3000/?q=portail' -H 'Origin: http://localhost:3000' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -H 'Content-Type: application/json; charset=utf-8' --compressed
```
response:
```
[{"id":2,"feature":{"id":1,"name":"hello_world","created_date":"2018-12-11T20:55:38.891097Z","initial_value":null,"description":null,"default_enabled":false,"type":"FLAG","project":1},"feature_state_value":null,"enabled":true,"environment":2,"identity":null}]
```

**Closed** 2018-12-19 17:17 UTC
